#!/usr/bin/env python3
"""Regenerate data/unicode-math.tsv from unicode-math-table.tex.

Usage:
    tools/gen_unicode_math.py [unicode-math-table.tex] > data/unicode-math.tsv

Without an argument the table is located with kpsewhich (TeX Live, MiKTeX).
The table ships with the unicode-math LaTeX package
(https://github.com/latex3/unicode-math), distributed under the LPPL 1.3c.
"""

import re
import subprocess
import sys

ROW = re.compile(
    r'\\UnicodeMathSymbol\{"([0-9A-Fa-f]+)\}\{\\(\S+?)\s*\}\{\\(\w+)\}\{(.*)\}%?\s*$'
)


def locate_table():
    try:
        out = subprocess.run(
            ["kpsewhich", "unicode-math-table.tex"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        out = ""
    if not out:
        sys.exit("unicode-math-table.tex not found; pass its path as an argument")
    return out


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else locate_table()
    print("# Generated by tools/gen_unicode_math.py from unicode-math-table.tex,")
    print("# part of the unicode-math package (LPPL 1.3c):")
    print("# https://github.com/latex3/unicode-math")
    print("# Do not edit by hand; put additions in latex.tsv or extra.tsv.")
    print("#")
    print("# name\tcodepoint\tdescription")
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = ROW.match(line)
            if m:
                code, name, _cls, desc = m.groups()
                print("%s\tU+%04X\t%s" % (name, int(code, 16), desc.strip()))


if __name__ == "__main__":
    main()
