#!/usr/bin/env python3
"""Regenerate data/text.tsv: LaTeX text-mode accents and special letters.

Usage:
    tools/gen_text_tsv.py > data/text.tsv

Accents are written as in LaTeX: \\"o and \\"{o} give ö; letter-named accents
need braces (\\v{c} gives č, since \\vc would be a different command).  Only
combinations that exist as a single precomposed character are listed.
"""

import unicodedata

# LaTeX accent command -> combining mark
SYMBOL_ACCENTS = [
    ("`", "̀", "grave"),
    ("'", "́", "acute"),
    ("^", "̂", "circumflex"),
    ("~", "̃", "tilde"),
    ("=", "̄", "macron"),
    (".", "̇", "dot above"),
    ('"', "̈", "diaeresis (umlaut)"),
]
LETTER_ACCENTS = [
    ("u", "̆", "breve"),
    ("r", "̊", "ring above"),
    ("H", "̋", "double acute"),
    ("v", "̌", "caron (hacek)"),
    ("d", "̣", "dot below"),
    ("c", "̧", "cedilla"),
    ("k", "̨", "ogonek"),
    ("b", "̱", "macron below"),
]
LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

# Text-mode commands for letters and symbols (LaTeX2e, T1/TS1 encodings).
SPECIALS = [
    ("ss", "ß"), ("ae", "æ"), ("AE", "Æ"), ("oe", "œ"), ("OE", "Œ"),
    ("aa", "å"), ("AA", "Å"), ("o", "ø"), ("O", "Ø"), ("l", "ł"), ("L", "Ł"),
    ("i", "ı"), ("j", "ȷ"), ("dh", "ð"), ("DH", "Ð"), ("th", "þ"), ("TH", "Þ"),
    ("ng", "ŋ"), ("NG", "Ŋ"), ("dj", "đ"), ("DJ", "Đ"),
    ("textquestiondown", "¿"), ("textexclamdown", "¡"),
    ("guillemotleft", "«"), ("guillemotright", "»"),
    ("guilsinglleft", "‹"), ("guilsinglright", "›"),
    ("quotedblbase", "„"), ("quotesinglbase", "‚"),
    ("textquotedblleft", "“"), ("textquotedblright", "”"),
    ("textquoteleft", "‘"), ("textquoteright", "’"),
    ("textendash", "–"), ("textemdash", "—"), ("textellipsis", "…"),
    ("textbullet", "•"), ("textperiodcentered", "·"),
    ("textdegree", "°"), ("textmu", "µ"), ("texttimes", "×"), ("textdiv", "÷"),
    ("textsection", "§"), ("textparagraph", "¶"),
    ("textcopyright", "©"), ("textregistered", "®"), ("texttrademark", "™"),
    ("texteuro", "€"), ("textsterling", "£"), ("textyen", "¥"), ("textcent", "¢"),
    ("textordfeminine", "ª"), ("textordmasculine", "º"),
    ("textonehalf", "½"), ("textonequarter", "¼"), ("textthreequarters", "¾"),
]


def precomposed(letter, mark):
    text = unicodedata.normalize("NFC", letter + mark)
    return text if len(text) == 1 else None


def main():
    print("# Generated by tools/gen_text_tsv.py; edit that script instead.")
    print("# LaTeX text-mode accents (\\\"o, \\\"{o}, \\v{c}) and special letters.")
    print("# Format: name<TAB>symbol.")
    print()
    for cmd, mark, desc in SYMBOL_ACCENTS + LETTER_ACCENTS:
        print("# %s%s: %s" % ("\\", cmd, desc))
        for letter in LETTERS:
            text = precomposed(letter, mark)
            if not text:
                continue
            if not cmd.isalpha():
                print("%s%s\t%s" % (cmd, letter, text))
            print("%s{%s}\t%s" % (cmd, letter, text))
        print()
    print("# Letters and symbols")
    for name, text in SPECIALS:
        print("%s\t%s" % (name, text))


if __name__ == "__main__":
    main()
